name: Daily README Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update README
        run: |
          echo "Last updated on $(date -u)" >> README.md

      - name: Commit and push
        run: |
          git config user.name "syedturabb"
          git config user.email "syedturabb@users.noreply.github.com"
          git add README.md
          git commit -m "🤖 Daily README update" || exit 0
          git push
